version: "3.7"

services:
  tor:
    image: bogny/tor:latest
    restart: always
    #ports:
    #  - "9050:9050" # Tor proxy
    #  - "9051:9051" # Tor control port
    networks:
      - backend

  instaraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ~/tmp/
        target: /data
    environment:
      - http_proxy=socks5://tor:9050
      - https_proxy=socks5://tor:9050
    networks:
      - backend

networks:
  backend:
    name: app